import type { Metadata } from "next";

import "./globals.css";

import { GeistMono } from "geist/font/mono";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistMono.className} antialiased min-h-screen`}>
        {children} <Footer />
      </body>
    </html>
  );
}
